services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # JWT Authentication Service Configuration
    App\Service\AuthService:
        arguments:
            $fromEmail: '%env(MAIL_FROM_ADDRESS)%'
            $tokenExpiryHours: 24
            $maxLoginAttempts: 5
            $lockoutDurationMinutes: 30
