framework:
    cache:
        # Unique name of your app: used to compute stable namespaces for cache keys.
        prefix_seed: 'iamgickpro_app'

        # Use filesystem for caching (no Redis required)
        app: cache.adapter.filesystem
        
        # Namespaced pools for different cache types
        pools:
            # Stock media cache pool with longer TTL
            stock_media.cache:
                adapter: cache.adapter.filesystem
                default_lifetime: 3600  # 1 hour default
            
            # System cache pool for general application caching
            system.cache:
                adapter: cache.adapter.filesystem
                default_lifetime: 1800  # 30 minutes default
