lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    # JWT token time-to-live in seconds (86400 = 24 hours)
    # Consider increasing this for production (e.g., 2592000 = 30 days)
    token_ttl: 86400
    user_identity_field: email
